### ISSUE TITLE
Several AssetsControllerTests broken

### ISSUE THREAD

**Issue by legobeat** [MetaMask/core#1010]
Some integration and unit tests fail when run locally on the package but ignored or silenced in CI.

Some of these are due to fetching from live endpoints which are deprecated (Infura returning errors for Ropsten testnet) or have differing behavior (Goerli tokens are now tracked at `https://token-api.metaswap.codefi.network`).

[test.log](https://github.com/MetaMask/controllers/files/10182883/test.log)

Related:
#413
#988

**Comment by desi** [comment]
Believe this is fixed with #1499
