### ISSUE TITLE
NetworkController API normalization: rename `properties` state to `networkDetails`

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1019]
We should rename the `properties` state to `networkDetails`, to more closely align with the extension network controller. Of the two, `networkDetails` was chosen because it's more descriptive of the state contents. This state is a collection of properties about the network that we have discovered at runtime (i.e. they are not configured or statically set).

This is part of [a larger effort to normalize the API of both network controllers](https://github.com/MetaMask/controllers/issues/971), to make them easier to merge.

**Comment by mcmire** [comment]
This was closed in #1074.
