### ISSUE TITLE
NetworkController API normalization: Make `getEIP1559Compatibility` method async

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1022]
We should add an async `getEIP1559Compatibility` method that populates the `networkDetails` (aka `properties`) state if it's not set yet.

This is useful in cases where other parts of the codebase need to guarantee this state is set before proceeding.

This is part of [a larger effort to normalize the API of both network controllers](https://github.com/MetaMask/controllers/issues/971), to make them easier to merge.

**Comment by kenhkan** [comment]
Marking this as Done. See https://github.com/MetaMask/core/commit/68b88b8c8d519480652b0c86b761db3c7e139589

**Comment by kenhkan** [comment]
Closing since this has been fixed by https://github.com/MetaMask/core/pull/1084.
