### ISSUE TITLE
Tests should not create a NetworkController instance where possible

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/core#1051]
Many unit tests create an instance of the network controller when they could easily be mocking out functionality of it. The tests would benefit most from this change:

- [x] TokensController (https://github.com/MetaMask/core/pull/1050)
- [x] NftController (https://github.com/MetaMask/core/pull/1052)
- [x] NftDetectionController (https://github.com/MetaMask/core/pull/1053)
- [x] TokenDetectionController (https://github.com/MetaMask/core/pull/1062)
- [x] TokenListController (https://github.com/MetaMask/core/pull/1061)

**Comment by BelfordZ** [comment]
it appears gh doesnt like my use of `partially fixes #ISSUE NUMBER`

what would be the appropriate keyword to use so that gh doesnt auto close this issue every time a PR is merged from the list

**Comment by Gudahtt** [comment]
I think it sees the "Closes #___" part, and doesn't pay attention to what comes before that.

I've used "Relates to ___" in past. It doesn't result in any linking.
