### ISSUE TITLE
Investigate function impact of replacing web3-provider-engine

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1065]
We should investigate the functional changes that will result from replacing `web3-provider-engine` with the extension's network client.

### Scope:
- "network methods", i.e. anything the network client tests cover

### Action plan:
- Discover differences by running network client tests against web3-provider-engine
- Document differences
- Decide what to do on a case-by-case basis

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-621e46b4d7103800171d1b02/issues/MetaMask/core/1065?planning-poker) with Zenhub @Gudahtt @mcmire @xinnanyemm

**Comment by Gudahtt** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-621e46b4d7103800171d1b02/issues/MetaMask/core/1065?planning-poker) with Zenhub @cryptodev-2s

**Comment by kenhkan** [comment]
Only remaining item: the mobile difference list

**Comment by mcmire** [comment]
@BelfordZ For the nonce tracker, does https://github.com/MetaMask/core/pull/1147 being merged now change anything going forward? i.e. you say after `web3-provider-engine` is removed, calls to getTransactionCount are no longer cached, but would that still be the case?

**Comment by BelfordZ** [comment]
@mcmire yes, thank you for pointing that out. #1147 will resolve the difference as it pertains to the transaction controller. More broadly speaking, other calls to eth_getTransactionCount that might exist (or received through dapp api) still wont be cached, though. I will update with the above considerations.

**Comment by BelfordZ** [comment]
@mcmire upon further inspection, it seems we still need to update mobile to add some middleware that calls the transactionControllers nonce tracker when handling getTransactionCount, similar to how we do it in extension: 
 - [metmask-controller calls createMetamaskMiddleware](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js#L1278)
  - [createMetamaskMiddleware handles eth_getTransactionCount](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/createMetamaskMiddleware.js#L38)
  
With just #1147 - the nonce tracker wont get used when the requests to the method eth_getTransactionCount are coming through the provider.

**Comment by mcmire** [comment]
Makes sense @BelfordZ!

**Comment by Gudahtt** [comment]
Regarding the `eth_getTransactionCount` method, I have a draft branch on mobile that should ensure that behaves the same as before. I've just left a comment here about it: https://github.com/MetaMask/mobile-planning/issues/798#issuecomment-1505919649
I can handle it as part of that issue

**Comment by Gudahtt** [comment]
>If provider type is localhost or rpc, chainId will be the value in the provider config. If you use setProviderType with providerType localhost (which doesn't allow setting chainId), chainId will be 0x0.

>If the chainId in providerConfig is alphanumeric, but not valid hex, it will now throw.

Note that as of #1064, we have validation in place to ensure custom networks have a valid hex chain ID set. So this scenario should no longer be possible.

The situation with Localhost is weird though. That built-in localhost network isn't used by mobile, nor would it be useful for the extension. I'll make a note to remove that at some point.

**Comment by Gudahtt** [comment]
Regarding block ref rewriting, note that only `latest` is rewritten to use the latest block number (on extension currently, and after replacing web3-provider-engine). `pending` and `earliest` and all other block tags are left as-is.

**Comment by Gudahtt** [comment]
I believe that `encryption_public_key` is unaffected by the web3-provider-engine replacement. It shouldn't work today in the network controller because the implementation of that method relies upon `encryptionPublicKey` being passed into web3-provider-engine, but we don't pass it in.

I guess it might throw a different error now at least. But both before and after, it would throw an error.

There are a bunch more methods in the same situation (anything referenced here basically: https://github.com/MetaMask/web3-provider-engine/blob/cf612f898002833c36730d23972fe4c4dd483c76/subproviders/hooked-wallet.js#L700)

**Comment by Gudahtt** [comment]
It seems that these methods used to be intercepted by web3-provider-engine, but are now forwarded to the RPC endpoint:
- `net_listening`
- `web3_clientVersion`
- `eth_filter`/`eth_subscribe`-related methods

**Comment by mcmire** [comment]
I've updated the Notion doc to incorporate all of the comments above. I also did another audit of the differences before and after replacement, and noticed a change in behavior with the `eth_signTypedData` methods. Take a gander at the doc here and leave a comment if you see anything out of place: https://www.notion.so/Report-Functional-impact-of-replacing-web3-provider-engine-514c2e4694d24acbbf9182d12fc01c6b

**Comment by mcmire** [comment]
@Gudahtt Are we good with this now?

**Comment by mcmire** [comment]
@Gudahtt Ah fair. I have to run out for a bit here but I'll focus on fixing the conflicts on that PR when I get back. And then I'll get to the sanitization middleware PR 😅

**Comment by Gudahtt** [comment]
I have reviewed the diff for #1116 again, and I believe this document is complete. Everything seems to be accounted for.

**Comment by mcmire** [comment]
Marking this as done!
