### ISSUE TITLE
Migrate nonce-tracking from `web3-provider-engine` to transaction controller

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1070]
The transaction controller currently relies on the `nonce-tracker` middleware in `web3-provider-engine` to ensure that the suggested nonce used is greater than any pending transactions.

We should switch to using the `nonce-tracker` library for this purpose instead, like the extension does.

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-621e46b4d7103800171d1b02/issues/MetaMask/core/1070?planning-poker) with Zenhub @Gudahtt @mcmire @cryptodev-2s

**Comment by adonesky1** [comment]
We're not aiming to add a `pendingTransactionsController` [as well](https://github.com/MetaMask/metamask-extension/blob/9f89d71c6f71d93e63e4aedc7287ff73db351d86/app/scripts/controllers/transactions/index.js#LL191C5-L191C26) are we? Its not clear to me how this functionality is mirrored on the core side
