### ISSUE TITLE
Remove `EthQuery.sendAsync` check from NetworkController

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1076]
The `lookupNetwork` and `getEIP1559Compatibility` methods in NetworkController check to see if the EthQuery object which is assigned when a provider is initialized has a `sendAsync` method before looking up the network or determining EIP-1559 compatibility. This check is unnecessary, as EthQuery will always have this method. We can remove this check and the associated tests.

This issue was split off from https://github.com/MetaMask/core/pull/1039.

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1076?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @mcmire
