### ISSUE TITLE
Analyze differences between extension and mobile keyring interactions

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1102]
We should analyze the differences between the "keyring interaction" code on extension v.s. mobile.

On extension, keyring interactions are handled by functions in `metamask-controller.js`. On mobile, they are in `@metamask/keyring-controller`.

**Comment by mikesposito** [comment]
The following is a list of functions in the metamask-extension client that interact with the EthKeyringController. 
The list is divided into semantic categories, taken directly from the extension: They are not meant to indicate classes or nested objects.

**HD Keyring** 
- [ ] addNewAccount
- [ ] verifySeedPhrase
- [ ] removeAccount
- [ ] importAccountWithStrategy

**KeyringController**
- [ ] setLocked
- [ ] createNewVaultAndKeychain
- [ ] createNewVaultAndRestore
- [ ] exportAccount

**Vault**
- [ ] submitPassword
- [ ] verifyPassword

**QR Devices**
- [ ] submitQRHardwareCryptoHDKey:
- [ ] submitQRHardwareCryptoAccount:
- [ ] cancelSyncQRHardware:
- [ ] submitQRHardwareSignature:        
- [ ] cancelQRHardwareSignRequest

**Hardware Keyrings**
- [ ] connectHardware
- [ ] forgetDevice
- [ ] checkHardwareStatus
- [ ] unlockHardwareWalletAccount
- [ ] setLedgerTransportPreference
- [ ] attemptLedgerTransportCreation
- [ ] establishLedgerTransportPreference

I will compare these methods between clients in separated comments to follow

**Comment by mikesposito** [comment]
## HD Keyring Methods differences

### addNewAccount
* The extension `addNewAccount` takes an `accountCount` parameter: a new account is added only if its value is equal to the number of identities in the preferences controller store.  In the core KeyringController we don’t have this parameter and the account is directly added to the primary keyring. This has been done to make this method idempotent for MV3 compatibility reasons (See [Pull Request #15566](https://github.com/MetaMask/metamask-extension/pull/15566))
* The extension `addNewAccount` method returns the keyring memState along with preferencesController identities in the store. On the other hand, the core KeyringController `addNewAccount` returns only the keyring memState, returned by calling the `fullUpdate()` method.

Besides these two differences the clients add a new account on the primary keyring in the same way.

### verifySeedPhrase
* In the extension, the primary keyring mnemonic is handled as buffer. In the core KeyringController it is handled as a string.

Besides that, the methods are aligned.

### importAccountWithStrategy
* API for this method are different, as  `strategy` argument keys used to identify strategies are different: es. “Private Key” in the extension, “privateKey” in the core KeyringController
* For strategy private key, additionally to `isValidPrivate`, the extension  has also this check (See [Pull Request #17763](https://github.com/MetaMask/metamask-extension/pull/17763)): 
> `getBinarySize(prefixedPrivateKey) !== 64 + ‘0x’.length`  

These are the only two differences.

### removeAccount
* After calling `EthKeyringController.removeAccount`, there’s a check to see if it is the last account of a keyring: if so, the `keyring.destroy()` method is directly called. (See: [Pull Request #14993](https://github.com/MetaMask/metamask-extension/pull/14993)) - maybe we could do something on the `eth-ledger-bridge-keyring` to remove the direct call from the extension?
* In the extension `removeAllAccountPermissions` gets called as well, to remove all permissions associated with the removed account

**Comment by mikesposito** [comment]
## “KeyringController” methods differences
### setLocked
* In the extension, the `ledgerKeyring.destroy()` and `trezorKeyring.dispose()` methods are called to lock hardware keyrings.
* For MV3 compatibility, in the extension  `clearLoginArtifacts()`  is also called to remove login data from the browser session storage.

### createNewVaultAndKeychain
* To resolve a “possible bug” and to avoid potential multiple submissions from the UI, on the extension there’s a check to see if the vault has been already created by checking accounts in the EthKeyringController (See: [Pull Request #2605](https://github.com/MetaMask/metamask-extension/pull/2605))

### createNewVaultAndRestore
* In the extension, the seed phrase is passed as argument to this method, on core monorepo as a string
* Besides clearing the addresses in the preferencesController (done also on mobile side), we call the following “clearing” controllers methods:
	* `snapController.clearState`
	* `notificationController.clear`
	* `accountTracker.clearAccounts`
	* `cachedBalancesController.clearCachedBalances`
	* `txController.txStateManager.clearUnapprovedTxs`
It seems these are not called in the core KeyringController createNewVaultAndRestore method.
* In the extension, after creating a new vault, accounts are restored up until the first found with 0 balance (that is then removed)
* In the extension, the  `transportPreference` for the ledger keyring is also updated 

### exportAccount
The methods are aligned.

**Comment by mikesposito** [comment]
## Vault methods differences
### submitPassword
* After submitting the password to `EthKeyringController.submitPassword`, there is a check for the latest block.
* Despite the comment on the method, on extension it seems like we don’t update the preferencesController with new accounts
* In the extension, the  `transportPreference` for the ledger keyring is also updated 

### verifyPassword
* The method is not present in the core KeyringController

One interesting difference: in the extension we call `EthKeyringController.verifyPassword()` to check the password, while in the core KeyringController we compare the password passed as argument to `exportAccount` with `EthKeyringController.password`.
As  `EthKeyringController.password` is undefined when locked, does it mean that when locked we can export an account passing `undefined` to this function on mobile?

**Comment by mikesposito** [comment]
## Hardware Keyrings
These methods are not yet present on the core KeyringController (albeit some methods linked to hardware keyrings support are being added, see: [Pull Request #1121](https://github.com/MetaMask/core/pull/1121)). I will go through a description of they do

### getKeyringForDevice(deviceName, hdPath = null)
This function is not exported to the extension UI, but it is used by all the others to get an hardware keyring from `EthKeyringController.getKeyringsByType` to then call specific keyring methods, using `deviceName` (read: keyring.type).

In case of a Trezor device, it also sets the Trezor model on appStateController

### connectHardware(deviceName, page, hdPath)
A method to get the previous, next or first page of accounts from an hardware device and then syncing the accountTracker with them.

Returns a list of account

### forgetDevice(deviceName)
Calls `keyring.forgetDevice()`

### checkHardwareStatus(deviceName, hdPath)
Returns true if an hardware device is unlocked, using `keyring.isUnlocked()`

### unlockHardwareWalletAccount(index, deviceName, hdPath, hdPathDescription)
Unlocks an account at index `index` from an hardware keyring with type `deviceName`. Then builds a label for each of the accounts found using the preferencesController.

Returns a joint object of identities from preferencesController state and EthKeyringController’s memStore

### setLedgerTransportPreference(transportType)
Updates the ledger transport method in the preferencesController and calls `keyring.updateTransportMethod` if there is a ledger keyring instance in EthKeyringController. It falls back to the original value in case of error.

### attemptLedgerTransportCreation()
Gets the ledger keyring and calls `keyring.attemptMakeApp()`

### establishLedgerTransportPreference()
Calls `setLedgerTransportPreference` with the current transport preference

**Comment by mikesposito** [comment]
## Use of the PreferencesController
The extension makes use of the PreferencesController to update, sync or remove addresses (identities), to set the selected address and to label accounts.

These interactions are all supported on the core KeyringController as it accepts these “options” on the constructor:
* `removeIdentity`: called `removeAccount` on extension’s PreferencesController
* `updateIdentities`: called `setAddresses` on the extension
* `setSelectedAddress`: called the same on the extension
* `setAddressLabel`: called the same on the extension

So we should be able to easily instantiate the core KeyringController from the extension passing the corresponding PreferencesController methods to its constructor.

**Comment by mcmire** [comment]
@mikesposito This is great analysis!

One thing is that you've looked at MetamaskController in extension, but the equivalent in mobile is Engine.js. Is it worth looking at how the keyring controller is being interacted with there as well? I don't know if you ended up looking at that anyway through your analysis, but I thought I'd point it out.

**Comment by mikesposito** [comment]
@mcmire this is a good point! 
In metamask-mobile's Engine.js we just instantiate the core KeyringController (`@metamask/keyring-controller`) and interact with the underlying eth-keyring-controller through it.

On the other hand, on metamask-extension, we instantiate eth-keyring-controller directly and interact with it, duplicating the logic the is now in the core's KeyringController

**Comment by mcmire** [comment]
Ah gotcha, that makes sense. I'm good on this then!
