### ISSUE TITLE
Convert the ENS controller to the BaseController v2 API

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1130]

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1130?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @mikesposito

**Comment by Gudahtt** [comment]
Completed in #1134
