### ISSUE TITLE
NFTs from ERC1155 are not imported in Testnets

### ISSUE THREAD

**Issue by jarnaez728** [MetaMask/core#1142]
I'm developing several ERC1155 smart contracts and when I try to import to MetaMask Mobile some NFT an error message appears indicating that I'm not the owner of the NFT. This happens at least with Binance Testnet and Mumbai. I've not tried yet in mainnet.

**Steps to reproduce the behavior**
1. I deploy a ERC1155 contract in a Testnet
2. I send some NFT to an address
3. From MetaMask mobile I try to import the NFT indicating contract address and NFT Id
4. An error appears indicating I'm not the owner

![IMG_D7117FF78DD5-1](https://user-images.githubusercontent.com/6360717/213201369-58df1938-47a3-4e39-b7a1-6ab33c94032d.jpeg)

You can see [here](https://testnet.bscscan.com/token/0x9559A3C6c89e26880271d4AaC74ED9A7085366ac) an example of one contract. When I try to import the NFT, for example with id 6, in the account 0x15fb3cd012fab51be9ce9af8109e8580aaf153f9 the error message attached appears.

If to test yourselves the bug I need to send some NFT to some address, please let me know.

**Expected behavior**
The NFT is imported in MetaMask showing the right metadata (image, title and description) following the proper json file defined in the uri.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Mini
 - OS: iOS16.2
 - App Version: 5.12.3

**Comment by jarnaez728** [comment]
In the last browser extension (v 10.28.1) the import of NFT works great (with the exception of the bug #6068), so it seems a problem in mobile version

**Comment by jarnaez728** [comment]
I think this problem has been solved and it doesn't happen in v7.8.0 although I have to perform additional testing.

**Comment by sahar-fehri** [comment]
Hello everyone,
Tested this on Android version 7.12.3, on Goerli testnet and i am able to import my NFT.
Tested also IOS v 7.12.5 and i am able to import my NFT.

You think we can close this one?

cc @tommasini @jarnaez728 @rekmarks

**Comment by jarnaez728** [comment]
Hi, I can confirm now is working fine so I think this bug can be closed. I imported an NFT (ERC1155) from Mumbai. The only problem is that the name of the collection appears as Unnamed collection ("Colección sin nombre" in Spanish). In any case I think this is a missing feature of Metamask, not a bug. I don't know if it is in some roadmap but it would be nice to have.
![IMG_AAC2492E1DA6-1](https://github.com/MetaMask/core/assets/6360717/c774f6fe-e53b-43a8-ae3a-cd68ff4f379c)

**Comment by jarnaez728** [comment]
I just saw that what I said it already has a bug opened: https://github.com/MetaMask/metamask-mobile/issues/6068
