### ISSUE TITLE
Stub PreferencesController in core KeyringController unit tests

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/core#1151]
Currently the core KeyringController unit tests instantiate a full PreferencesController before each run.
We should instantiate the KeyringController used for tests with stub functions instead.

This is part of the effort to merge extension and mobile keyring interactions.

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1151?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @mikesposito
