### ISSUE TITLE
Change test structure in core KeyringController 

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/core#1152]
Currently, unit tests for core KeyringController are not divided by targeted method, making it hard to establish the methods affected by a change.

We should group tests by the tested KeyringController method.

This is part of the effort to merge extension and mobile keyring interactions.

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1152?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @mikesposito
