### ISSUE TITLE
Plan tasks to merge the transaction controllers

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1155]
We should plan the tasks needed to merge the two transaction controllers. Ideally we should plan these tasks so that the work can be done in small, measurable pieces. We can make these controllers behave more similarly to each other bit-by-bit until the final step of replacing the extension controller with the core controller is small enough for a single task/PR.

Likely we will have tasks focused on adding/modifying features, and some on normalizing the APIs, and some on cleaning up tests and adding test coverage where it is missing. We will need to create test plans to cover functionality not easily covered by automated tests as well (e.g. hardware wallet integrations).

**Comment by cryptodev-2s** [comment]
**### 1 - Normalize Controller State**
_The state on Mobile holds both local and incoming transactions state/history the data stored is as below:_

```
TransactionState {
  transactions: TransactionMeta[];
  methodData: { [key: string]: MethodData };
}

TransactionMeta {
  isTransfer?: boolean;
  transferInformation?: {
    symbol: string;
    contractAddress: string;
    decimals: number;
  };
  id: string;
  networkID?: string;
  chainId?: Hex;
  origin?: string;
  rawTransaction?: string;
  time: number;
  toSmartContract?: boolean;
  transaction: {
    chainId?: Hex;
    data?: string;
    from: string;
    gas?: string;
    gasPrice?: string;
    gasUsed?: string;
    nonce?: string;
    to?: string;
    value?: string;
    maxFeePerGas?: string;
    maxPriorityFeePerGas?: string;
    estimatedBaseFee?: string;
    estimateGasError?: string;
 };
  transactionHash?: string;
  blockNumber?: string;
  deviceConfirmedOn?: WalletDevice;
  verifiedOnBlockchain?: boolean;
  status: TransactionStatus;
  error: Error (in case of failed tx status)
}

MethodData {
    registryMethod: string;
    parsedRegistryMethod: Record<string, unknown>;
}
```

_Whereas the extension behaved differently it uses two different controllers TransactionController for Local Transactions and IncomingTransactionController for Incoming Transactions._

**The state in the TransactionController is as below:**

{
   [txId]: {
     custodyStatus: string;
    custodyId?: string;
    blockNumber?: string;
    id: number;
    time: number;
    contractMethodName: string;
    customTokenAmount: string;
    dappProposedTokenAmount: string;
    dappSuggestedGasFees?: DappSuggestedGasFees;
    currentTokenBalance: string;
    originalApprovalAmount: string;
    finalApprovalAmount: string;
    type: TransactionType;
    originalType: TransactionType;
    status: TransactionStatus;
    metamaskNetworkId: string;
    loadingDefaults: boolean;
    txParams: {
      from: string,
      to: string,
      nonce: string,
      value: string,
      data: string,
      gas: string,
      gasPrice: string,
      maxFeePerGas: string,
      maxPriorityFeePerGas: string,
      type: string,
      estimateSuggested: string
      estimateUsed: string
    };
    txReceipt: TxReceipt;
    history: Record<string, any>[];
    origin: string;
    originalGasEstimate: string;
    userEditedGasLimit: boolean;
    nonceDetails: Record<string, any>;
    hash: string;
    v?: string;
    r?: string;
    s?: string;
    submittedTime?: number;
    txErr?: TxError;
    }
} 

**The state in the IncomingTransactionController is as below**
```
{
    incomingTransactions:                { [hash]:{
    blockNumber:       string;
    id:                number;
    chainId:           string;
    metamaskNetworkId: string;
    status:            string;
    time:              number;
    txParams:          TxParams;
    hash:              string;
    type:              string;
} };
    incomingTxLastFetchedBlockByChainId: { [chainId]: block ) };
}
```
