### ISSUE TITLE
NetworkController API normalization: Make internal methods and properties private

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1177]
Private network controller method and properties are handled inconsistently between extension and mobile right now. We should ensure that all internal methods and properties are private, using the hash syntax rather than the `private` keyword.

This is part of [a larger effort to normalize the API of both network controllers](https://github.com/MetaMask/controllers/issues/971), to make them easier to merge.

The related extension issue is here: https://github.com/MetaMask/metamask-extension/issues/18588

### **Definition of Done**
- [ ] Whenever applies, any change unit tested, reviewed(approved) and documented(JSDOC at least)
- [ ]  We have changelog entries for any related changes
- [ ]  Any changed APIs have comprehensive inline documentation
- [ ]  Any changed public APIs are well covered by unit tests

**Other items**
- [ ]  If a planning/research ticket, then the plan has been reviewed and approved by at least 1 team members

**Comment by Parthib314** [comment]
Hey @Gudahtt, Can I work on it??
