### ISSUE TITLE
NetworkController: Remove `NetworkController:providerConfigChange` controller event

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1205]
This event is unnecessary for the following reasons:

1. There does not seem to be a reference to this event outside of the `core` codebase.
2. It is improperly named, as it is not fired immediately after the provider configuration object is changed, but rather after `network` in state is updated with the network ID.

**Comment by Gudahtt** [comment]
Note that `providerConfigChange` is called in some scenarios when the provider config didn't actually change. For example, it can indicate initialization has completed.
