### ISSUE TITLE
NetworkController: Remove `setActive` option from `upsertNetworkConfiguration`

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1259]
There are too many methods that can be used to switch networks, and as a result we have a LOT of tests for NetworkController. It is not difficult for consumers to call `setActiveNetwork` after calling `upsertNetworkConfiguration` if they wish to switch to a newly added or updated network. Therefore to minimize the test suite, we should remove this option from `upsertNetworkConfiguration`.

**Comment by Gudahtt** [comment]
This is obsolete as of https://github.com/MetaMask/core/pull/4286, which removed `upsertNetworkConfiguration`
