### ISSUE TITLE
Why is the wait time higher for fast than slow

### ISSUE THREAD

**Issue by zhengyimeng** [MetaMask/core#1424]
我看到你们的代码写的等待时间，是快速地多余慢速的等待，这是个 bug 吧？
<img width="506" alt="image" src="https://github.com/MetaMask/core/assets/20783425/a180c485-6cb2-4145-964c-c9ed00f242a3">

**Comment by desi** [comment]
GasFeeController. Translation is: "I saw that the waiting time written in your code is faster than slow waiting. Is this a bug?"

**Comment by vinistevam** [comment]
Thank you for your contribution!
The issue has been resolved as we now use the gas-API to fetch the suggested gas fees.

I'm closing this PR, but please feel free to reach out if you have any questions or need further clarification

![Image](https://github.com/user-attachments/assets/6edae66f-0f96-419e-9a64-406bd4b53d11)
