### ISSUE TITLE
[network-controller] Replace provider config with selected network client ID

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1462]
The provider configuration state is a duplication of the configuration of the current selected network (either built-in or custom). Rather than duplicate this information in state, we can track the current selected network with an ID instead.

This would make the state smaller, and would simplify the validation of this state.

The provider configuration state is used throughout the client repositories, but it can be easily recreated from an ID using a selector. We should consider adding a "getSelectedNetworkConfig" method to the controller to make referencing this state easier from the extension background as well (where we can't use selectors as easily).

**Comment by Gudahtt** [comment]
We should consider adding the client ID state first, then removing the provider config later. Adding the client ID is simple and unblocks other work, whereas removing the provider config might require significant refactors on the clients.

**Comment by adonesky1** [comment]
> We should consider adding the client ID state first, then removing the provider config later. Adding the client ID is simple and unblocks other work, whereas removing the provider config might require significant refactors on the clients.

We should create a ticket for removing the providerConfig since we pursued the approach described above: adding the selectedNetworkClientId without removing the providerConfig
