### ISSUE TITLE
Update Token List Controller to use new API endpoint

### ISSUE THREAD

**Issue by hesterbruikman** [MetaMask/core#1519]
### Background
On the token list controller, there is an endpoint used to fetch a list of tokens. Download of the total list is 2.2 Mb of data. After fetching this list, the Mobile app filters this list by duplicate symbols. This process is increasing app load time.

### Proposed solution
Remove the tokens filter logic from the core repo side. The codefi team has added parameters to enable this. Resulting in a total list of 1000 tokens for 66 kb. This will result in a more performative app but also will reduce server costs and less need for bandwidth for our mobile users.

### Technical Details
Core repo changes:

On token-service.ts changegetTokensURL for the new endpoint
On TokenListController.ts delete line 280 filteredTokenList to line 297 (this logic is on the api side now)
Do the necessary changes for this to work as with the previous endpoint
Mobile changes:
Suggestion (We should aim to instead of creating a patch, update the assets-controller version instead):

Create a patch with the changes above

### Acceptance Criteria
- [ ] Update endpoint (https://token-api.metaswap.codefi.network/tokens/1?occurrenceFloor=3&includeNativeAssets=false&includeDuplicateSymbolAssets=false&includeTokenFees=false&includeAssetType=false)
- [ ] Remove logic to filter tokens

The token list should be working the exact same way as it was.
Scenario: Token list on token detection feature

GIVEN a user is in wallet view
WHEN a user does have tokens to import
THEN it should show those tokens (Token detection feature)
Scenario: Token list on token detection feature

GIVEN a user is in wallet view
WHEN a user tries to import a token manually
THEN it should be able to find the token by the name

**Comment by hesterbruikman** [comment]
@tommasini could you please add any details as needed?

cc @Gudahtt

**Comment by tommasini** [comment]
Forgot that this issue was already created here https://github.com/MetaMask/metamask-mobile/issues/6030, should we remove this one or the other one?

**Comment by hesterbruikman** [comment]
@Gudahtt Is this issue still on your radar? Is it helpful to have this separate ticket in this core repo?

**Comment by Gudahtt** [comment]
Thanks for the reminder! This had slipped my mind. I will add it to this upcoming sprint, and I will close the other duplicate ticket

**Comment by Gudahtt** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1519?planning-poker) with Zenhub @cryptodev-2s @mcmire
