### ISSUE TITLE
Fully migrate `json-rpc-engine` into core monorepo

### ISSUE THREAD

**Issue by xinnanyemm** [MetaMask/core#1550]
We would like to migrate the [`json-rpc-engine`](https://github.com/MetaMask/json-rpc-engine) library into this repo to make it easier to maintain.

See the following checklist for instructions on accomplishing this: https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740

**Comment by Gudahtt** [comment]
Note that `json-rpc-engine` has a number of PRs pending from rekmarks that we'd like to preserve, but not before merging the repo. We should migrate those branches/PRs into core so that they aren't lost

**Comment by mcmire** [comment]
Reopening since this isn't done yet!
