### ISSUE TITLE
Fully migrate `json-rpc-middleware-stream` into core monorepo 

### ISSUE THREAD

**Issue by xinnanyemm** [MetaMask/core#1552]
We would like to migrate the [`json-rpc-middleware-stream`](https://github.com/MetaMask/json-rpc-middleware-stream) library into this repo to make it easier to maintain.

See the following checklist for instructions on accomplishing this: https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740

**Comment by Gudahtt** [comment]
At a glance, it looks like the repository updates needed are:
* Update Yarn from v1 to v3
* Update TypeScript to v4.6.3

**Comment by xinnanyemm** [comment]
Michele, Desi, and Kanthesha will discuss and break down into smaller PRs.

**Comment by kanthesha** [comment]
Are we looking for any specific version of Yarn 3? By default it is 3.6.3.
