### ISSUE TITLE
Add `typescript` `>= 4.6.3` as an optional peer dependency for each package in the monorepo

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1563]
We expect that consumers that are using a package in this repo are using TypeScript >= 4.6.3, which supports the `import { type X }` syntax. See: https://github.com/MetaMask/metamask-extension/pull/19659#discussion_r1272209469

**Comment by MajorLift** [comment]
Closing as all core packages are using `>4.6.3` for typescript.
