### ISSUE TITLE
Add missing methods to `KeyringController`

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/core#1595]
These methods should be added to `KeyringController` to remove the use of `EthKeyringController` from `SnapController`, `MMIController`, `DecryptMessageController` and enable the use of hardware keyrings in the extension:

- [x] https://github.com/MetaMask/core/pull/1591
- [x] https://github.com/MetaMask/core/pull/1594
- [x] https://github.com/MetaMask/core/pull/1596
- [x] https://github.com/MetaMask/core/pull/1574

**Comment by mcmire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1595?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @mikesposito
