### ISSUE TITLE
Migrate `@metamask/eth-json-rpc-provider` to core monorepo  

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/core#1685]
As part of Shared Libraries Q3 OKRs, the team would like to migrate [`@metamask/eth-json-rpc-provider`](https://github.com/MetaMask/eth-json-rpc-provider) libraries into this monorepo to make it easier to maintain.

See [#1079 comment](https://github.com/MetaMask/core/issues/1079#issuecomment-1700126302) for instructions on accomplishing this.

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1685?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @kanthesha @MajorLift @mikesposito
