### ISSUE TITLE
Shared Libraries - 2023/Q4/O1/KR3 - Create and apply consistent patterns across controllers for multichain support

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1782]
Our controllers use a variety of different patterns for data-polling, none of which support simultaneous use of multiple networks. We should update all of them to use one consistent polling pattern that supports simultaneous use of multiple networks. 

There may be additional patterns which need to be applied or help needed in order to support the ongoing multichain effort.

**Comment by mobularay** [comment]
Just aligned with @mcmire : 

- this epic represents the supporting role that SL team is playing wrt the multichain controllers upgrade that the DevEx team is doing, represented by this epic ["DevEx: Refactor Controllers for Multichain (Amon Hen)"](https://app.zenhub.com/workspaces/-mm-roadmap--deliverables-pi--core-63cfddd70e3a7b00253424a7/issues/gh/metamask/metamask-planning/1018)
- this epic is not completely broken down yet; @mcmire will be connecting with @adonesky1 early week of Oct 23rd to align on scope between the two teams

**Comment by vandan** [comment]
DevEx team ended up getting to this body of work before Shared Libraries had capacity for it.
Closing the Epic in favor of this DevEx Epic: https://github.com/MetaMask/MetaMask-planning/issues/1018
