### ISSUE TITLE
Simplify PermissionLogController API

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1824]
PermissionLogController is a controller in the extension. Before migrating this controller to this repo, we need to review how PermissionLogController is currently being used in the extension and review the current API. Then we can design a new API that is as minimal as possible and apply that to the TypeScript version of PermissionLogController.

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1824?planning-poker) with Zenhub @cryptodev-2s @kanthesha @MajorLift @mcmire

**Comment by Tura187** [comment]
Yo ........


((THATS CRAZY KID ))...
WOW MY ex girlfriend is that good ..
That's sounds like some CiA type 
SH..... Inside  greys anatomy where we teleported to find a frog with hair 
To help heal little Timmy from a out - [ ] break of Skittle syn-dron-yi-al-colie-stai ces..........🤣😅😆🤣😂 


Thank you very much
