### ISSUE TITLE
Copy TypeScript version of PermissionLogController (from extension) along with tests into this repo

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1826]
PermissionLogController, a controller in the extension, is written in JavaScript. We need to copy over the code, converting it to TypeScript along the way. We want to copy over the tests as well (taking care not to refactor them yet).

**To decide:** This controller can either be located in `@metamask/permission-controller` (since it's related to permissions) or we can create a new package.

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1826?planning-poker) with Zenhub @cryptodev-2s @kanthesha @MajorLift @mcmire
