### ISSUE TITLE
Explore solutions for transferring issues and PRs from other repos into the core monorepo

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#1835]
## Explanation

Once a library has been migrated into the core monorepo, its original repo is archived and sunsetted. Before that happens, we want to preserve the issues and PRs that are in the original repo by transferring them into the monorepo. 

We will explore and compare solutions (e.g. bash script, third-party tool, GitHub API or `gh`) for fetching the issues and pull requests and recreating them on the monorepo. 

## Requirements

- The solution must be easily reusable for any library migration.
- We may want to ensure that there's some indication for future readers (e.g. prefix, non-user author) that the transferred issues/PRs were copied from another repo.

## Resources
- Third-party, open-source solution: https://github.com/NicholasBoll/github-migration
- Challenges in automating the transfer process: https://github.com/michaelgwelch/migrate-issues

**Comment by MajorLift** [comment]
@mcmire I created an issue for this!

**Comment by mcmire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1835?planning-poker) with Zenhub @MajorLift @kanthesha

**Comment by MajorLift** [comment]
Following discussion with @mcmire @Gudahtt, we'll be opting against recreating all of the source repo's issues/PRs/branches in core. 

- The archived source repo is sufficient for historic preservation purposes.
- Open issues: move to core using the `Transfer Issues` feature.
- Open PRs:
  - Investigate using migration tool to recreate in core. 
  - If that's impractical, ask author to re-open and add link to previous discussion in the original PR.

**Comment by MajorLift** [comment]
Following discussion with @mcmire @Gudahtt, we'll be opting against recreating all of the source repo's issues/PRs/branches in core. 

- The archived source repo is sufficient for historic preservation purposes.
- Open issues: move to core manually using the `Transfer Issues` feature.
- Open PRs: ask author to re-open PR in core, and add link to the original PR for context on the previous discussion. 

- Possibly investigate in new ticket: Recreate open PRs in core using the migration tool, and instruct original author to add new commits to the recreated branches.
