### ISSUE TITLE
Nit: Since this file exports a function called `createQueuedRequestMiddleware`, should this file also be called `createQueuedRequestMiddleware.ts`?

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/core#1863]
Nit: Since this file exports a function called `createQueuedRequestMiddleware`, should this file also be called `createQueuedRequestMiddleware.ts`?

_Originally posted by @mcmire in https://github.com/MetaMask/core/pull/1806#discussion_r1364087236_
            
            
Same applies to SelectedNetworkMiddleware

**Comment by MajorLift** [comment]
Closing as stale.
