### ISSUE TITLE
Expose SafeEventEmitterProvider as a value, not just a type

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1974]
This is so that we can use this to create a fake provider object, as in the network clients in NetworkController (see https://github.com/MetaMask/core/pull/1116, `packages/network-controller/tests/fake-provider-engine.ts`, for the original source)

**Comment by MajorLift** [comment]
Closed by https://github.com/MetaMask/core/pull/1738.

Relevant comments:
- https://github.com/MetaMask/core/pull/1738#discussion_r1357548245
- https://github.com/MetaMask/core/pull/1738#discussion_r1357561065
- https://github.com/MetaMask/core/pull/1738#discussion_r1357566155
