### ISSUE TITLE
`json-rpc-engine`: Support cancelation

### ISSUE THREAD

**Issue by safareli** [MetaMask/core#1994]
Would be nice if `handle` returns some object which represents running request with a method `abort` which aborts the request, like [XMLHttpRequest.abort()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort)

**Comment by MajorLift** [comment]
Looks like a WONTFIX issue?
- https://github.com/MetaMask/metamask-extension/issues/4225#issuecomment-754882813

**Comment by MajorLift** [comment]
Closing as WONTFIX.

**Comment by mcmire** [comment]
Yes, for context, in order to be able to cancel a request now with [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193), `request` would have to take a signal from AbortController. A change would have to be submitted via a new EIP.
