### ISSUE TITLE
Research and design "network" abstraction that can be used instead of network client

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#2005]
The network client is a bit too low-level to be used directly. When working with a network client, especially resolving a network client ID, you have to be aware that there are two types: an Infura network client and a custom network client. This bifurcation is necessary to have at some level because of the fact that we have two different middleware stacks (one designed for Infura RPC endpoints, one designed for everything else) and thus two kinds of network client configuration objects. However, if you just want to make a request to the network, you shouldn't have to care what kind of network it is, as we can expect that all networks feature the same JSON-RPC API. Also, if you want any information about the network, such as the native currency symbol or the nickname, you currently have to shoehorn extra properties into the network client configuration. This shouldn't be necessary, as the middleware doesn't care about them.

Consumers — in particular the DevEx team, who are running into problems with the current design while implementing multichain initiatives — would have a better time if instead of using a network client, they used an abstraction on top of it. We could call it "network", and it would essentially be the same as a network client now, except that the network client interface would be abstract, and network configuration would be allowed to hold user-provided properties.

The devil is in the details, of course, so this ticket is dedicated to understanding whether this plan is really feasible or not, and if so, how much work it would create.

## Examples

This is a list of changes we've had to make which solve immediate problems but are ultimately undesirable and which we aim to fix with this proposal. Please add to this list as you find more examples!

- https://github.com/MetaMask/core/pull/2000/files#diff-02c32f437b122b5c71f0ac6bdf304cd22f6d4569c9c9b8ecbb711c11c98cd0d3R111
- https://github.com/MetaMask/core/pull/1794

**Comment by Gudahtt** [comment]
Alternatively, we could use network configuration for built-in networks as well: https://github.com/MetaMask/core/issues/1279

**Comment by Gudahtt** [comment]
We discussed adding a `getNetworkConfiguration(networkClientId)` action as a short-term fix, and consolidating `setActiveNetwork` and `setProviderType`. These two things should reduce the friction of dealing with these two types of networks.

Longer-term we discussed enhancing the custom network configuration/middleware to support Infura (as covered in #1279).

**Comment by mcmire** [comment]
Tickets created: https://github.com/MetaMask/core/issues/2019 and https://github.com/MetaMask/core/issues/2020.

I will leave this ticket here in case it comes in handy later, but I will deprioritize it.

**Comment by Tura187** [comment]
I am the owner of Tura11
Tura 187 
Tura 11541 on git hub 
X keeps hacking and stealing my s***

**Comment by Tura187** [comment]
Ok she knows how to reprogram software she changed up my JSon files to stop reading  my web 3 wallets on my Mac book 
Phone etc etc she is also been destroying devices 
Been hacking terrorizing my digital and physical well being 

She is stilling from me ..

**Comment by Tura187** [comment]
I think you a low level headed little Network client information giver

**Comment by Tura187** [comment]
I work 12 hours a day I was building this program for myself I didn't think so I had somebody hacking me I was taking my time I was figuring it out yes yes I'm low levels on the information I knew about it but as I keep on messing around with it more knowledge I gained the more I can move the more I started paying attention to things I didn't need anybody that was hacking in my business you people helped her come up with n u l L's web web digital bypassers

**Comment by Tura187** [comment]
HISTORY


The person that is doing the hacking on the other end of my metamask and digital wallets
Her name is Amber Wilbur also goes by Amber Stephens
Also go by Amber Cole
Her aunt is my neighbor she lived with her aunt she's been hacking me every single day all night stalking me she's been stalking me since February of last year before I even started even having a relations with her

I CREATED THIS GITHUB TURA 11
SHE GOT INTO IT AND STARTED HACKING IT NOT THINKING IT WAS HER NOT PUTTING IT TWO AND TWO TOGETHER THAT CLOSE
I STARTED A DIFFERENT REPERTOIRE CALLED
THERE'S A PORTAL IN MY BACKYARD
THAT'S MINE AS WELL I WANT IT BACK

**Comment by desi** [comment]
@mcmire and @Gudahtt we believe this is handled now. We are closing but if our understanding is incorrect please feel free to reopen.
