### ISSUE TITLE
[base-controller] fix: `any` usage

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#2026]
## Explanation

The `Action`, `Event` types in `BaseController` currently rely on explicit `any` usage. These types are used across most of our libraries. A more rigorous overhaul of these definitions will help us implement features with more type-safe code. 

## Background

- On why `(...args: never[]) => unknown` is the universal supertype for functions: 

The return type of the supertype function needs to be `unknown` (universal supertype), and the parameters need to be `never` (universal subtype). This is because in general `(x: SuperType) => T` is a *subtype* of `(x: SubType) => T`. So the params need to be the narrowest type (i.e. `never`) for the function type to be widened into the universal function supertype. 

- There's an example of this in the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types).
- And here's a more detailed [reddit comment](https://www.reddit.com/r/typescript/comments/muyl55/comment/gv9ndij/?utm_source=share&utm_medium=web2x&context=3) on this topic.

**Comment by Tura187** [comment]
Look they're both my metamask githubs dude she's hacked one of them took it over and I can't get back in it tura11
Tura 11541

**Comment by Tura187** [comment]
Git hub 
Tura11

GitHub 11541
