### ISSUE TITLE
Update ComposableController to BaseController v2

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#2082]
ComposableController still inherits from BaseController v1. In order to build a wallet library, we need to make all of our controllers consistent, and that means we need to migrate this controller to BaseController v2.

Please use https://github.com/MetaMask/core/pull/1705 (PhishingController) as a recent reference for this type of migration.

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/2082?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @MajorLift @mcmire @mikesposito
