### ISSUE TITLE
[assets-controllers] Retry failed token rate requests

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#2084]
When the token rates controller tries to update token rates and fails, we should retry that request if appropriate. This would improve our changes of getting usable token rates, ensuring that users don't need to wait for the next cycle if they encounter an intermittent failure. This would increase network traffic somewhat, but it would give us confidence in increasing the polling interval further without leaving users "stuck" with no rates if they happen to encounter an intermittent failure.

If the response indicates that the request was rate-limited, and includes a wait time, we should wait the appropriate amount of time before retrying. Otherwise, we should use an exponential backoff strategy of some sort, to avoid overwhelming the server.

We should also ensure that retry attempts are halted if the polling that triggered this request in the first place has been stopped.

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/2084?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @MajorLift @mcmire @mikesposito
