### ISSUE TITLE
Add script for updating changelogs of a release candidate

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#2085]
It would be useful to have a script that could update changelogs for a release canddiate, after changes have been merged into the main branch. The changelogs get updated automatically by our `create-release-branch` tool, but subsequent changes have to be applied manually at the moment. This would simplify the process for keeping a release candidate up-to-date.

We may find it useful to update all packages at once, or just individual packages.

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/2085?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @MajorLift @mcmire @mikesposito
