### ISSUE TITLE
Reconfigure gh-pages docs publishing

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/core#221]
Looks like this no longer gets updated via CI, `gh-pages` hasn't been updated in 6 months.

(I imagine this is because of a token issue.)

**Comment by rekmarks** [comment]
Meanwhile, I just deleted the `gh-pages` branch and thereby unpublished the docs page (https://metamask.github.io/controllers).

**Comment by desi** [comment]
We have another issue that represents this work. #1845
