### ISSUE TITLE
KeyringController state issues

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/core#35]
There's something funky going on with the state of the `KeyringController`. Specifically with the property `keyrings`.

Once the property is updated via `fullUpdate` which internally calls `update`, the new value is not accessible via state (still has the default value) but it's fine if you access it via context.

How to reproduce from the app:
1  - Log in
2 -  To verify that the value has been set, log `Engine.context.KeyringController.state.keyrings` => `[{ type: 'HD Keyring', accounts: ['0x...']}]` 
3 - Now try to access it through state,  log`Engine.state.KeyringController.keyrings` =>  `[]`

**Comment by desi** [comment]
We believe the KeyringController has changed significantly since this issue was opened and feel this issue is outdated. If the original author has additional context or believes it is still an issue please feel free to reopen.
