### ISSUE TITLE
[assets-controllers] Prevent redundant token rate updates

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#3605]
The `TokenRatesController` will unnecessarily update the token rates in some situations. Efforts have been made in the past to reduce the occurrences of this, but a few remain.

One example is that updates to `allDetectedTokens` can trigger a token rate update, even when the list of token addresses actually used remains unchanged. The code as written assumes that `allDetectedTokens` is always updated immutably, but that doesn't appear to be the case (and even if it was, changes to metadata would still unnecessarily trigger updates).

We can solve this by calculating the list of token addresses each time we notice a state change that might require an update. We can compare the list of addresses before and after the change to determine whether an update is needed. This should effectively prevent all unnecessary token rate updates from being triggered.

**Comment by mcmire** [comment]
I'm willing to take this on after I finish with #3600.
