### ISSUE TITLE
[composable-controller] Make class and messenger generic upon child controllers

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#3627]
## Explanation

Currently, the allow lists of `ComposableControllerMessenger` are set to `string`, which is too permissive. Each `ComposableController` instance needs typing and allow lists that are specific to its set of input child controllers.

However, there's no simple way to achieve this using `BaseController`, as controller-messenger allow lists are defined for the controller class singleton, not controller instances.

Instead, `ComposableController` and `ComposableControllerMessenger` need to be made polymorphic upon the `controllers` constructor property, which represents the list of child controllers to be composed. 

## Requirements

- A generic parameter `ControllerList` (or maybe `ChildControllers`) needs to be added to the `ComposableController` class and `ComposableControllerMessenger` type.
- `ControllerList` should be constrained, but not defined by the least supertype for all base-controller instances (currently `ControllerInstance`).
- ~`ControllerList` should be used to derive the return type of `flatState()` at the type level.~
- `ControllerList` should be used to derive the state type for `ComposableController` instances.
- `ControllerList` should be used to derive the allow lists of `ComposableControllerMessenger`. 
  - The allow lists should at minimum include the `stateChange` events for all child controllers that are subscribed to in the `#updateChildController()` method. 

## References

- See https://github.com/MetaMask/core/pull/3590#discussion_r1414460107

**Comment by MajorLift** [comment]
One approach we could take is to write a factory class for ComposableController:

```ts
abstract class ComposableControllerFactory {
  static compose<
    ChildControllers extends ControllerInstance[],
    
    ComposedState extends ComposableControllerState = T1<ChildControllers>,
    
    ComposedStateChangeEvent = ControllerStateChangeEvent<'ComposableController', ComposedState>
    
    ChildStateChangeEvents extends EventConstraint & { type: `${string}:stateChange` } = T2<ChildControllers>,
    
    ComposedControllerMessenger = RestrictedControllerMessenger<
      'ComposableController',
      never,
      ComposedStateChangeEvent | ChildStateChangeEvents,
      never,
      ChildStateChangeEvents['type']
    >,
  >({
    controllers: ChildControllers, 
    controllerMessenger: ComposedControllerMessenger, 
  }){}
}
```

This would have several advantages:
- Removing state updates that rely on side effects from consideration, which makes it easier to reason about pure type-level logic.
- Reducing the only independent variable to the list of child controllers.
- Narrowing the scope of the problem to typing each ComposableController instance only once -- upon instantiation.

The API of the ComposableController class would change as follows:
- Before:
```ts
const composableControllerMessenger = controllerMessenger.getRestricted({
  name: 'ComposableController',
  allowedEvents: ['FooController:stateChange'],
});
const composableController = new ComposableController({
  controllers: [fooController],
  messenger: composableControllerMessenger,
});
```

- After:
```ts
const { composedController } = ComposableControllerFactory.compose<[fooController, barController]>({
  controllers: [fooController, barController], 
  controllerMessenger,
});
```

**Comment by desi** [comment]
@MajorLift How would you feel about changing the estimate on this reflect the actual complexity? And just wondering what the next steps on this one are?
