### ISSUE TITLE
[token-detection-controller] Remove limit on number of tokens that can be detected

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#3661]
Currently, the `detectTokens` method in `TokenDetectionController` has a hardcoded upper limit of 2000 on the number of tokens it can process. 
- This logic should be rewritten so that any number of tokens can be processed in batches of 1000. 
- Unit tests need to be written.

**Comment by DhifallahOussema** [comment]
Hello, I'm intrested in this issue and wanted to know if I'm still able to solve it.
I thought about a possible approach where we run a loop that splits the `tokensToDetect` into slices of 1000 token each.
Please let me know if it's still available so I can add a PR.
