### ISSUE TITLE
Plan work to upgrade TransactionController to BaseControllerV2

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#3707]
Considering that converting TokenDetectionController to BaseController v2 took longer than expected due to unforeseen changes, we want to be more conscientious about converting TransactionController.

Figure out all of the changes we would want to make in upgrading this controller and create new tickets as necessary.

**Comment by mcmire** [comment]
Here are the necessary changes to TransactionController that we would have to make:

- Replace `hub` property and replace with messenger pattern
  - Remove `TransactionControllerEventEmitter` type
  - Introduce new events and event types:
    - `TransactionController:stateChange` (`TransactionControllerStateChangeEvent`)
      - You can use the `ControllerStateChangeEvent` utility type to create the type; see DetectTokensController for an example
    - `TransactionController:incomingTransactionBlockReceived` (`TransactionControllerIncomingTransactionBlockReceivedEvent`)
    - `TransactionController:postTransactionBalanceUpdated` (`TransactionControllerPostTransactionBalanceUpdatedEvent`)
    - `TransactionController:speedUpTransactionAdded` (`TransactionControllerSpeedUpTransactionAddedEvent`)
    - `TransactionController:transactionApproved` (`TransactionControllerTransactionApprovedEvent`)
    - `TransactionController:transactionConfirmed` (`TransactionControllerTransactionConfirmedEvent`)
    - `TransactionController:transactionDropped` (`TransactionControllerTransactionDroppedEvent`)
    - `TransactionController:transactionFailed` (`TransactionControllerTransactionFailedEvent`)
    - `TransactionController:transactionFinished` (`TransactionControllerTransactionFinishedEvent`)
    - `TransactionController:newSwapApproval` (`TransactionControllerNewSwapApprovalEvent`) (?)
      - Not sure what this event is supposed to represent, so may want to rename it to be more readable
    - `TransactionController:newSwap` (`TransactionControllerNewSwapEvent`) (?)
      - Not sure what this event is supposed to represent, so may want to rename it to be more readable
    - `TransactionController:transactionPublishingSkipped` (`TransactionControllerTransactionPublishingSkippedEvent`)
    - `TransactionController:transactionRejected` (`TransactionControllerTransactionRejectedEvent`)
    - `TransactionController:transactionStatusUpdated` (`TransactionControllerTransactionStatusUpdatedEvent`)
    - `TransactionController:transactionSubmitted` (`TransactionControllerTransactionSubmittedEvent`)
    - `TransactionController:unapprovedTransactionAdded` (`TransactionControllerUnapprovedTransactionAddedEvent`)
  - Introduce `TransactionControllerGetStateAction` type
    - You can use the `ControllerGetStateAction` utility type to create this; see DetectTokensController for an example
  - Introduce `TransactionControllerControllerEvents` type, set to a union of the above types
  - Introduce `TransactionControllerControllerActions` type, set to `TransactionControllerGetStateAction`
  - Update `TransactionControllerMessenger` to allowlist the above events and actions
  - Replace `this.hub.emit` calls by emitting the above events instead
  - Remove `this.hub.emit` calls for the following events:
    - `${transactionMeta.id}:finished` event — the consumer can listen to `TransactionController:transactionFinished` and check the ID of the transaction
    - `${transactionMeta.id}:speedup` event — the consumer can listen to `TransactionController:speedUpTransactionAdded` and check the ID of the transaction
    - `${transactionMeta.id}:publish-skip` event — the consumer can listen to `TransactionController:transactionPublishingSkipped` and check the ID of the transaction
    - `${transactionMeta.id}:confirmed` event — the consumer can listen to `TransactionController:transactionConfirmed` and check the ID of the transaction
- Have TransactionController inherit from `BaseController` instead of `BaseControllerV1`
- Rename `TransactionState` to `TransactionControllerState` for consistency with other controllers
- Create a `transactionsControllerMetadata` variable which holds metadata for all state variables
  - See AccountsController for an example
- Rename `TransactionConfig` to `TransactionControllerOptions`; convert to `interface`, and remove supertype; add `state` and `messenger`
- Update constructor to take a single options object of type `TransactionControllerOptions`
- Extract default state set in constructor to `getDefaultState` function
  - See UserOperationController for an example
- Instead of setting `name` as an instance property, pull it to the top as a constant called `controllerName`, and then use `typeof controllerName` anywhere you need the type version
  - See TokenDetectionController for an example
- Instead of setting `this.defaultState` in constructor, and instead of calling `super` with `config` and `state`, call `super` with `messenger`, `name: controllerName`, `metadata`, `state: { ...getDefaultState(), ...state }`, and then remaining options
  - See AccountsController for an example
- Don't call `this.initialize()` as it doesn't exist anymore
- Update state update callsites
  - All calls to `this.update(...)` need to be updated so that instead of a copied-but-modified version of the state, a function is passed which directly modifies a deep copy of the state
  - See `NetworkController.lookupNetworkByClientId` for an example

Here are the necessary changes to the TransactionController tests that we would have to make:

- Perform slight refactors to controller setup code to better match existing conventions
  - The test suite (specifically, the `newController` helper) uses one of two different messenger objects depending on the scenario. This is clunky, and it would be better to just have one messenger object. In other tests, e.g. those for AccountsController, we have a `setupXController` helper, which is intended to take the same options that the controller constructor takes. It also builds a default messenger using a `buildXControllerMessenger` helper (which itself uses a `buildMessenger` helper internally) if one is not passed. Although this is not the final pattern we want to use, it would be better to go in this direction so that we are closer to our ideals.
- Update `waitForTransactionFinished` function to subscribe to a messenger instead of the controller

Here are changes that we should not make:

- Care must be taken to not convert any of the callbacks that the constructor takes (`getCurrentAccountEIP1559Compatibility`, `getCurrentNetworkEIP1559Compatibility`, etc.) to messenger actions. We can do this in another PR.
- IncomingTransactionHelper and PendingTransactionTracker both emit events. We don't need to convert these to messenger actions, because these events are only listened to internally.

**Comment by Gudahtt** [comment]
Oh, actually, I have just taken a look and I can see that all of these events are used externally. I hadn't realized we used so many, nevermind!

This plan looks good to me :+1:

**Comment by MajorLift** [comment]
Looks good overall! Some additions:
- Rename private properties to use the `#` prefix instead of the `private` keyword, so that they're encapsulated at runtime.
- Explicitly enumerate package-level exports in `index.ts` so that `controllerName`, `AllowedActions` etc. can be exported for internal usage (e.g. in test files).
- RE not converting callbacks: if any of the new events change state in other controllers which is then used by transaction-controller tests or methods/actions, it might be less of a pain (or even unavoidable) to convert some callbacks e.g. `getNetworkState` or methods e.g. `getChainId()` to use the messenger (along with consolidating `newController/buildMessenger`). It doesn't seem like there are many such interactions between controllers in the current tests, but if new tests need to be written for the new events, this could change.

**Comment by mcmire** [comment]
Okay great, thanks for the feedback! I think I have enough to go on in order to continue with the work. I've created a new ticket for it here: #3758
