### ISSUE TITLE
`base-controller`: Replace use of `any` with proper types (non-test files only)

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#3715]
Look for the following string in non-test files to find these: ``// TODO: Replace `any` with type``

These are occurring in BaseControllerV1 - so we are deciding to not address this.

**Comment by MajorLift** [comment]
Both instances are examples where `as any` is used to add new properties at runtime. This is a use case that will be listed as acceptable in the TypeScript guidelines `any` section. 

We could replace the TODOs with comments that explain this fact and point to `contributor-docs`. This would serve as a good example case for 2024/Q1/O2/KR2. 

If we go ahead with this approach, we should add https://github.com/MetaMask/contributor-docs/issues/47 as a blocker for this ticket.
