### ISSUE TITLE
`controller-utils`: Replace use of `any` with proper types (non-test files only)

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#3717]
Look for the following string in non-test files to find these: ``// TODO: Replace `any` with type``

At time of writing, there were 6 instances.

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/3717?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @kanthesha @MajorLift @mcmire

**Comment by mcmire** [comment]
Investigate whether `args` on `query` can be changed along with the return type.

**Comment by desi** [comment]
For this ticket we will not handle the query function. There will be a separate ticket for that. This one will handle the 5 straight forward fixes.
