### ISSUE TITLE
[preferences-controller] React to keyring state changes

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#3794]
The `PreferencesController` should listen for `KeyringController` state changes, and react to them appropriately. Specifically it should listen for account additions and removals, and ensure the selected address always points at an address that exists.

Today it doesn't react to these event changes because it relies upon the `KeyringController` calling the `PreferencesController` methods to update state. This is error prone and makes the `KeyringController` more complex than we'd like, and introduces a circular dependency between the controllers that would be nice to avoid.

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/3794?planning-poker) with Zenhub @Gudahtt @kanthesha @MajorLift @mcmire
