### ISSUE TITLE
[preferences-controller] Remove unused PreferencesController methods

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#3795]
After completing https://github.com/MetaMask/core/issues/3794 and https://github.com/MetaMask/core/issues/3699, I expect the methods `syncIdentities` and `updateIdentities` to no longer be used. These unused methods should be removed.

**Comment by desi** [comment]
This ticket has a blocking ticket but can be worked on. Just don't merge until "React to keyring state changes" has merged.
