### ISSUE TITLE
[composable-controller] Remove `flatState` getter

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#3812]
We should remove the `flatState` getter, and in general stop using flatted controller state in our applications.

We have found that the use of flattened controller state has made it difficult to identify where certain state properties come from, has caused property overlap problems between controllers, and in general has made our lives difficult for no benefit. Last I checked it was only used in one place, in the mobile project.

**Comment by desi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/3812?planning-poker) with Zenhub @Gudahtt @kanthesha @MajorLift @mcmire @mikesposito
