### ISSUE TITLE
[assets-controllers] TokenDetectionController uses the wrong token list

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#3905]
The TokenDetectionController will always use the token list for the current globally selected network, even when detecting tokens on a different network. Effectively it won't work when polling non-selected networks.

We should update the controller to use the token list for the network we're detecting tokens on.

**Comment by adonesky1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DevEx-63bee08a4e3b9d001108416e/issues/MetaMask/core/3905?planning-poker) with Zenhub @BelfordZ @jiexi @shanejonas
