### ISSUE TITLE
Spike: Explore Markdown parser

### ISSUE THREAD

**Issue by desi** [MetaMask/core#3921]
In order to determine if READMEs have all the information they need we would like to parse them. This ticket is a spike ticket to explore possible solutions/libraries.

**Comment by mcmire** [comment]
`unified`, `remark-parse`, and `mdast-util-from-markdown` are all made by the same author, so it makes sense that they would have the same output.

As a couple more options:

_ There is also `marked` which has a parser/lexer interface: https://marked.js.org/using_pro#lexer

_ The `markdown-it` package also has an API for parsing but I'm not sure how it works: https://markdown-it.github.io/markdown-it/#MarkdownIt.parse

I would say, let's try `mdast-util-from-markdown` as the interface seems pretty flexible, and the [AST](https://github.com/syntax-tree/mdast) is very well documented.
