### ISSUE TITLE
[assets-controllers] Make `Token` type json-serializable

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#3980]
The `Token` type defined in the `TokenRatesController` has a `balanceError` property, which is typed as `unknown`. This property is assigned an error value in the `TokensBalancesController` `updateBalances` method. 

`TokensController` uses the `Token` type in its state, which makes the state object non-json serializable. This is a roadblock for upgrading `TokensController` to `BaseControllerV2` and needs to be fixed.

**Comment by mcmire** [comment]
This does seem to be an issue anymore, as the `balanceError` property in the `Token` type seems to have been replaced with a `hasBalanceError` property, which is now a `boolean`. In addition, `TokensController` has been updated to `BaseController` v2.
