### ISSUE TITLE
Extract the detector from `eth-phishing-detect` to this repo

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#4026]
Currently, select parts of the `eth-phishing-detect` repo is under our codeownership. We added this because we wanted to make sure to approve any changes to the detector. However, this repo is different than our other repos in that several people contribute to it, and some are outside of Consensys. Therefore, this change has caused some concerns recently.

We had always planned to extract the detector to this repo so it that it could be maintained separately from the config. Now seems like a good time to do that.

**Comment by mikesposito** [comment]
Closed by https://github.com/MetaMask/core/pull/4137
