### ISSUE TITLE
Fix Flaky test for TransactionController -> multichain transaction lifecycle

### ISSUE THREAD

**Issue by desi** [MetaMask/core#4054]
It was reported in slack that `yarn workspace @metamask/transaction-controller run test` was failing for TransactionController. 

Examples of the failure can be found in the following: 

- https://github.com/MetaMask/core/actions/runs/8264565942/job/22608512716?pr=4032
- https://github.com/MetaMask/core/actions/runs/8263603598/job/22605489074

Screenshot:
<img width="1373" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlRaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1afb6006a89d0db5b0299380ace73d8396c9ebd/Screenshot%202024-03-13%20at%208.42.38%E2%80%AFAM.png" alt="Screenshot 2024-03-13 at 8.42.38 AM.png" />

**Comment by MajorLift** [comment]
Main branch CI run just failed due to this bug: https://github.com/MetaMask/core/actions/runs/8272378535/job/22634139461

**Comment by mcmire** [comment]
I don't think this problem is fixed. I'm still seeing this test fail intermittently.

**Comment by mcmire** [comment]
I haven't seen this problem happen in a while, so I'm going to close this for now and we can reopen if this pops up.
