### ISSUE TITLE
Token Rates request rate higher than expected

### ISSUE THREAD

**Issue by blurpesec** [MetaMask/core#4186]
#### Background
Starting in January, we migrated token pricing provider from Coingecko to an internal PriceAPI. At the time we were quoted a number of requests per day to expect once full rollout occurred. Currently we're doing ~10x that rate.

There has previously been some discussion around one or more of the apps possibly defaulting to an "open" state on browser load, regardless of if the app is "open" - which starts polling for token rates until the app is actually opened, then closed again.

#### Impact
The current impact of this is ~10x expected traffic to our internal Price API service which is a much higher-than-expected cost.

**Comment by desi** [comment]
Desi to discuss this with Gauthier about whether this should be investigated by the client teams. Need to have a lightweight step to gauge our volume.

**Comment by bergeron** [comment]
Expect an improvement in extension 11.16.0.  It will stop polling while MM is closed:

https://github.com/MetaMask/metamask-extension/pull/24021

**Comment by desi** [comment]
Will check back in with Michael on this after 11.16 is out for a bit to see if we are still seeing the issues.

**Comment by blurpesec** [comment]
This is fixed after 11.16.* rollouts. Traffic to PriceAPI reduced by ~85%.
