### ISSUE TITLE
Multichain Permission Adapter -> Maintain `wallet_getPermissions` backwards compatibility

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/core#4239]
When successful, `wallet_getPermissions` and `wallet_requestPermissions` both return the current permissions for the requesting subject, which is a subset of the permission controller's state. This is very unfortunate, because it means that we are externalizing the state of an otherwise internal module, and makes changes to its state breaking changes of our public API. In preparation for the introduction of a multichain API and its new permissions (see #4241), we should introduce an adapter function between the permission controller at the RPC methods that return its state.

This adapter function should take the permission controller state and return a public representation thereof, perhaps modeled on what we already do for [Snaps manifest permissions](https://github.com/MetaMask/snaps/blob/30c88f85bcc3c7987609fe1061756151e2a04ce9/packages/snaps-utils/src/manifest/validation.ts#L184-L241). We can then ship this public state representation as part of our API, and do whatever we want with our internal state. This public representation should focus on what's strictly necessary for the consumer to understand the authority they've been granted, and nothing more. In particular, it should not contain any ZCAP-LD properties or make mention of caveats, all of which we should regard as implementation details.

#### Complication: `window.ethereum`

Of course, we have _already_ shipped our current internal state via `window.ethereum` (and potentially the Snaps provider). The adapter must be written such that, for interfaces that support `wallet_getPermissions` and `wallet_requestPermissions` they return the same state that they do today, unmodified. If necessary, they can support newly introduced permissions as well, but we cannot break this APIs for existing consumers, and especially consumers of `window.ethereum`.

**Comment by vandan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wallet-API-Platform-63bee08a4e3b9d001108416e/issues/MetaMask/core/4239?planning-poker) with Zenhub @adonesky1 @BelfordZ @shanejonas

**Comment by vandan** [comment]
Migration should also be addressed along with this change: https://app.zenhub.com/workspaces/wallet-api-platform-63bee08a4e3b9d001108416e/issues/gh/metamask/metamask-planning/2530

**Comment by adonesky1** [comment]
There will already be chainId permissions in state for us to use.

**Comment by adonesky1** [comment]
Also 
`wallet_requestPermission`, `wallet_revokePermissions` included in the scope of this ticket
