### ISSUE TITLE
[Regression] yarn constraints check fails with consistent dependency versions set in manifests

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#4577]
## Severity

This affects all core dependency bumps.

## Description

The yarn constraints check (specifically the `expectConsistentDependenciesAndDevDependencies` method) [fails](https://github.com/MetaMask/core/actions/runs/10187664495/job/28182248938?pr=4576) even though version ranges are consistent across all manifest files in core repo workspaces.

## References

- Possibly introduced by https://github.com/MetaMask/core/pull/4546

## Acceptance Criteria

`yarn constraints` passes without errors iff. the versions specified for dependencies and devDependencies are consistent across all workspace manifest files.

**Comment by desi** [comment]
We missed updating in the PermissionsController. @cryptodev-2s
