### ISSUE TITLE
Add the new `default` snap dialog approval type to `ApprovalType`

### ISSUE THREAD

**Issue by GuillaumeRx** [MetaMask/core#4598]
The value should be `snap_dialog` as in `DIALOG_APPROVAL_TYPES` at https://github.com/MetaMask/snaps/blob/6a8b17be57123b7f8c65909154a701eea9abd09f/packages/snaps-rpc-methods/src/restricted/dialog.ts#L49

**Comment by ritave** [comment]
This issue is part of https://github.com/MetaMask/metamask-extension/pull/26304#discussion_r1701658713

After #4630 is released we should update the metamask-extension constant
