### ISSUE TITLE
Deprecate and re-release `@metamask/network-controller@21.1.0` as `22.0.0`

### ISSUE THREAD

**Issue by legobeat** [MetaMask/core#4838]
A breaking change was included in release of `@metamask/network-controller@21.1.0`. As discussed, we want to re-release it as correctly labelled `@metamask/network-controller@22.0.0`. 

This is blocking new releases of `@metamask/network-controller`.

**Comment by mcmire** [comment]
`@metamask/network-controller` 22.0.0 was published in [`core` release 228.0.0](https://github.com/MetaMask/core/releases/tag/v228.0.0). `@metamask/network-controller` 21.1.0 has now been deprecated: https://www.npmjs.com/package/@metamask/network-controller/v/21.1.0?activeTab=versions
