### ISSUE TITLE
SPIKE: Messenger Delegation

### ISSUE THREAD

**Issue by desi** [MetaMask/core#4986]
In order to improve developer velocity, help teams be more independent, reduce cross team code review and impact we should look into how we might support messenger delegation.

Today there are two messenger classes: the global messenger, and the restricted messenger. We use the restricted messenger to limit capabilities of controllers/services/etc in accordance with the principle of least authority, both to minimize complexity/risk and to ensure the right stakeholders are involved in granting capabilities. However, there is no way to delegate permissions from a restricted messenger. We can't pass capabilities through multiple hands (not with this system at least).

Instead, we can do away with the restricted/global distinction, and use just a single messenger class that can accept and delegate capabilities. This would let us establish multiple levels of capabilities, letting us arrange our codebase along team or process boundaries more easily. This would also make integration testing easier, by providing an obvious "boundary" for what to mock in an integration test that we can apply equally in all contexts.

The challenge with this will be in preserving rich types for each capability. Dynamic capability management is easy enough, but here we want to _statically_ know exactly which capabilities each instance has so all interactions can be type-checked.

**Comment by Gudahtt** [comment]
This spike has been completed, we have a new ADR for this now: https://github.com/MetaMask/decisions/pull/53
