### ISSUE TITLE
TokensController & CollectiblesController

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/core#516]
This work was conceived to help land the TokenRatesController in the extension. As it stands the TokenRatesController depends on the AssetsController, which is also not yet integrated into the Extension. Rather than adapting the AssetsController to make collectibles optional, It that the AssetsController can and should be broken out into a TokensController and a CollectiblesController. The primary reason for this being that Collectibles and Tokens live in separate pieces of the controllers state state and lumping them together makes the controller less modular, harder to reason about and maintain.

- [x]  Split out AssetsController into new separate TokensController and CollectiblesController
- [ ]  Convert both to V2

**Comment by desi** [comment]
These controllers were split and we have another ticket to handle the upgrade to BaseController V2. Closing this ticket. Please reopen if concerns.
