### ISSUE TITLE
TokenList unsafely handles potentially undefined return type

### ISSUE THREAD

**Issue by kumavis** [MetaMask/core#542]
https://github.com/MetaMask/controllers/blob/502bb2639ebc2a0b695671166f6747761e08795f/src/assets/TokenListController.ts#L271-L273

**Comment by kumavis** [comment]
typescript failing to save us bc typecasting
does typescript have templating/abstract types?
> safelyExecute<Token[]>(() => ...)
or something crazier like
> async function safelyExecuteWithTimeout(operation T) returnTypeOf(T) {...}

**Comment by desi** [comment]
We should stop the use of this function so we will close this one and #543 will cover it.
