### ISSUE TITLE
Migrate GoinGecko API interactions to separate module

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#625]
Our usage of CoinGecko should be extracted from the TokenRatesController and made into its own module. This module should be responsible for correctly formatting the request, and parsing the response and returning it in a sensible format.

This module should also handle any necessary validation, ensuring that an error is thrown if we don't get the information we want.

It should also be fully tested. And since it's no longer part of the TokenRatesController, we should remove any API-focused tests from the TokenRatesController test suite, and mock this new API module there instead of using network mocks.

**Comment by akp111** [comment]
Hey @Gudahtt , is it still a requirement? I would love to take it up

**Comment by mcmire** [comment]
@Gudahtt Is this effectively complete now, or is there anything missing with the current token service pattern that we still want to address?

**Comment by Gudahtt** [comment]
This was completed in #3600
