### ISSUE TITLE
Allow unauthorized requests to trigger user approval callback.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/core#725]
Allows lazier consumption of the resulting API: permissions could be requested as-needed.

Maybe added as an option?

As discussed in https://github.com/MetaMask/metamask-extension/issues/6110

**Comment by rekmarks** [comment]
We are not likely to support this feature for the ZCAP-LD-inspired permission system, especially given the direction of the multichain provider API, which enforces a model where all API endpoints need to be explicitly requested before they can be used. See [CAIP-25](https://github.com/ChainAgnostic/CAIPs/edit/main/CAIPs/caip-25.md).
