### ISSUE TITLE
Update test setup to reset and restore all mocks between each test

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#745]
Currently we are not setting [`resetMocks: true`](https://jestjs.io/docs/configuration#resetmocks-boolean) and [`restoreMocks: true`](https://jestjs.io/docs/configuration#restoremocks-boolean) within `jest.config.js`. We should enable this and remove calls to `jest.clearAllMocks()` and `jest.resetAllMocks()` within test files.

Note that this may require substantial changes for any test suites that rely heavily upon shared mocks.

**Comment by Gudahtt** [comment]
Update: We are setting `restoreMocks` today. But not `resetMocks`.
