### ISSUE TITLE
Use hexadecimal strings for chain ID

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#840]
We currently store the chain ID in different formats throughout MetaMask products and libraries. It can be a number, a decimal string,a `0x`-prefixed hexadecimal string, or a non-prefixed hexadecimal string.

We should converge on one standard way of representing a chain ID internally. The best of these three formats is the `0x`-prefixed hexadecimal string, because it's the only string format that is not ambiguous. The number format is inappropriate because some networks use chain IDs that exceed the maximum safe integer in JavaScript.

We could also consider using BigInteger, but that would require additional serialization that we are probably better off avoiding.

**Comment by desi** [comment]
No longer an issue. Closing because already completed.
