### ISSUE TITLE
Migrate off of `eth-*` and `ethjs-*` packages

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#852]
According to the [page for the `ethjs` org](https://github.com/ethjs), the `ethjs` packages are no longer maintained and `ethers` is suggested instead. The `ethjs` repo is also [archived](https://github.com/ethjs/ethjs). Finally, it is a bit of a pain to even work with these packages, as the `main` file for them (again, see [`ethjs`](https://github.com/ethjs/ethjs/blob/68229b93e72bfba0c9a37ea1d979347e8f7395e4/package.json#L225)) seems to link to the uncompiled version the library rather than the compiled version, and for the current version of `ethjs-query` that we are using, [this code contains Babel-specific code](https://unpkg.com/browse/ethjs-query@0.3.7/lib/index.js). We can upgrade to the latest versions of these packages, of course, and that would probably help us a little bit, but the point still stands that it will end up being a waste of time to keep using these libraries. They are right to suggest Ethers, because Ethers seems to be the best-maintained library when it comes to interactions with Ethereum (it also includes TypeScript types for all of its parts). We should consider switching fully to Ethers.

**Comment by ndevmetax** [comment]
> According to the [page for the `ethjs` org](https://github.com/ethjs), the `ethjs` packages are no longer maintained and `ethers` is suggested instead. The `ethjs` repo is also [archived](https://github.com/ethjs/ethjs). Finally, it is a bit of a pain to even work with these packages, as the `main` file for them (again, see [`ethjs`](https://github.com/ethjs/ethjs/blob/68229b93e72bfba0c9a37ea1d979347e8f7395e4/package.json#L225)) seems to link to the uncompiled version the library rather than the compiled version, and for the current version of `ethjs-query` that we are using, [this code contains Babel-specific code](https://unpkg.com/browse/ethjs-query@0.3.7/lib/index.js). We can upgrade to the latest versions of these packages, of course, and that would probably help us a little bit, but the point still stands that it will end up being a waste of time to keep using these libraries. They are right to suggest Ethers, because Ethers seems to be the best-maintained library when it comes to interactions with Ethereum (it also includes TypeScript types for all of its parts). We should consider switching fully to Ethers.


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by desi** [comment]
There are 2 technical proposals and the issues created for those should replace this. Closing.
