### ISSUE TITLE
Research on how to replace wildcard permissions in favour of permissions with caveats

### ISSUE THREAD

**Issue by GuillaumeRx** [MetaMask/core#887]
## Description
Wildcards are a kind of attenuation. Caveats are the means by which permissions are attenuated in ZCAP-LD. Everything we can do with wildcards can be done with caveats. Wildcards therefore add unnecessary complexity to the PermissionController, and should be removed in favour of caveats that provides easier readability.

## For example

The `getBip32Entropy` permission would become something like this:

### Before
```js
// PermissionController state
{
  `snap_getBip32Entropy_m/44'/1'`: { ... },
  `snap_getBip32Entropy_m/44'/60'`: { ... },
}
```

### After
```js
// PermissionController state
{
  `snap_getBip32Entropy`: {
    caveats: [
      {
        type: 'permittedPaths',
        value: [
          `m/44'/1'`,
          `m/44'/60'`,
        ]
    ]
  },
}
```

### Outcome
Result of this task should be a list of changes needed to remove wildcard support from PermissionController, all snap controllers and the changes needed for replacement of the permissions with caveat-based ones.

The report should be descriptive enough that the team can estimate the amount of work needed, either by amount of time or by story points.

**Comment by rekmarks** [comment]
Upon closer review, this issue is significantly complicated by our use of wildcard permissions for the snap permissions themselves. For example, the permission to communicate with the Filecoin snap currently looks like this:
```json
"wallet_snap_npm:@chainsafe/filsnap": {
    "caveats": null,
    "date": 1654882874322,
    "id": "Y34wk3O654MSvS1hOwXs7",
    "invoker": "https://filsnap.chainsafe.io",
    "parentCapability": "wallet_snap_npm:@chainsafe/filsnap"
}
```

If we got rid of wildcards, it would look something like this instead:
```json
"wallet_snap": {
    "caveats": [{
      "type": "snapIds",
      "value": {
        "npm:@chainsafe/filsnap": {
          "version": "1.0.0"
        }
      }
    }],
    "date": 1654882874322,
    "id": "Y34wk3O654MSvS1hOwXs7",
    "invoker": "https://filsnap.chainsafe.io",
    "parentCapability": "wallet_snap"
}
```

The good news is that we already ask people to use `wallet_enable` to connect to snaps, and that already conforms to what the API would look like with caveats instead of wildcards:
```js
async function connect () {
  await ethereum.request({
    method: 'wallet_enable',
    params: [{
      wallet_snap: { [snapId]: {} },
    }]
  })
}
```

Still, this significantly increases the scope of the refactor required on the Snaps side of things. We'll have to see how big and whether to proceed.

**Comment by Montoya** [comment]
We need to research this now because when we reach v1 release we will not be able to go back and change this

**Comment by kenhkan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/controllers/887?planning-poker) with Zenhub @david0xd @FrederikBolding @GuillaumeRx @hmalik88 @Mrtenz @ritave

**Comment by hmalik88** [comment]
Please see https://github.com/MetaMask/MetaMask-planning/issues/297
