### ISSUE TITLE
Change OpenSea Testnet chain to Goerli

### ISSUE THREAD

**Issue by nigimaxx** [MetaMask/core#919]
The OpenSea Testnet API now uses the Goerli Testnet work (https://docs.opensea.io/reference/testnets-api-overview#:~:text=Ethereum%20Goerli%20test%20network)

This causes issues when trying to import a NFT on a testnet. Loading the metadata of the contract currently always fails.

Changing the `RINKEBY_CHAIN_ID` constant to a `GOERLI_CHAIN_ID` constant would probably solve this issue.

https://github.com/MetaMask/controllers/blob/main/src/constants.ts#L9

**Comment by desi** [comment]
This was handled by #1041
