### ISSUE TITLE
Use exports [Event | Action].type instead of strings when subscribing and calling

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/core#921]
[Nit] What do you think about extracting this to a constant in NetworkController? This feels like the sort of knowledge that NetworkController should keep and expose to other places rather than copy around. Pro: more knowledge in one place. Con: Not sure if we've done that before for other controllers, so it would be a new pattern. Just a thought.

_Originally posted by @mcmire in https://github.com/MetaMask/controllers/pull/903#discussion_r980513388_

**Comment by desi** [comment]
Closing.
