### ISSUE TITLE
Replace `web3-provider-engine`

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#970]
We should replace `web3-provider-engine` with `json-rpc-engine` plus the network clients from the extension. This would get us closer to merging the two network controllers.

### Acceptance Criteria:
- Investigation is complete (https://github.com/MetaMask/core/issues/1065)
- Mobile is compatible with the `web3-provider-engine` replacement
- Mobile unit and e2e tests are passing with the `web3-provider-engine` replacement.

**Comment by kenhkan** [comment]
Zach's PR: https://github.com/MetaMask/core/pull/1116
